apiVersion: 1

contactPoints:
  - orgId: 1
    name: EventsNest Email Alerts
    receivers:
      - uid: eventsnest-email
        type: email
        settings:
          addresses: ${ALERT_EMAIL}
          singleEmail: true
