package group.moniepoint.eventsnestserver.storage;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.autoconfigure.condition.ConditionalOnBean;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import jakarta.servlet.http.HttpServletRequest;
import java.io.IOException;

/**
 * Local-dev only. Accepts the raw binary PUT that the frontend sends to the
 * "presigned" URL generated by {@link LocalFileStorageService#presignPut}.
 *
 * This controller is only registered when the local storage backend is active
 * ({@code app.storage.type=local}). In production (S3) it is absent entirely —
 * the FE uploads directly to the real S3 presigned URL without touching the server.
 */
@Slf4j
@RestController
@RequestMapping("/api/v1/storage/local-upload")
@RequiredArgsConstructor
@ConditionalOnBean(LocalFileStorageService.class)
public class LocalUploadController {

    private final LocalFileStorageService localStorage;

    @PutMapping("/{token}")
    public ResponseEntity<Void> upload(
            @PathVariable String token,
            @RequestHeader(value = "Content-Type", defaultValue = "application/octet-stream") String contentType,
            @RequestHeader(value = "Content-Length", defaultValue = "-1") long contentLength,
            HttpServletRequest request) {

        try {
            String publicUrl = localStorage.consumeUpload(token, contentType, contentLength, request.getInputStream());
            if (publicUrl == null) {
                log.warn("Local upload rejected — unknown or already-consumed token: {}", token);
                return ResponseEntity.status(HttpStatus.NOT_FOUND).build();
            }
            log.debug("Local upload complete — token={}, publicUrl={}", token, publicUrl);
            return ResponseEntity.ok().build();
        } catch (IOException e) {
            log.error("Local upload failed for token {}: {}", token, e.getMessage());
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }
}
