package group.moniepoint.eventsnestserver.seed;

import group.moniepoint.eventsnestserver.events.models.Events;
import group.moniepoint.eventsnestserver.programme.model.ProgrammeItem;
import group.moniepoint.eventsnestserver.programme.repository.ProgrammeItemRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.util.List;

@Slf4j
@Component
@RequiredArgsConstructor
public class ProgrammeSeeder {

    private final ProgrammeItemRepository programmeItemRepository;

    // ─── seed data ────────────────────────────────────────────────────────────

    private record ProgSeed(
            int organiserIndex, int eventIndex,
            String title, String description,
            String speakerName, String speakerBio,
            int offsetMinutes, int durationMinutes,
            int displayOrder) {}

    private static final List<ProgSeed> PROGRAMME_SEEDS = List.of(

            // TechFest Lagos 2026 (Akin, event 0)
            new ProgSeed(0, 0, "Opening Keynote: The Future of African Tech",
                    "Setting the vision for a decade of African-led technology innovation.",
                    "Akin Ogundimu", "Serial entrepreneur and co-founder of three Lagos-based startups.",
                    0, 60, 1),
            new ProgSeed(0, 0, "Panel: AI in Emerging Markets",
                    "How artificial intelligence is reshaping healthcare, finance, and agriculture across Africa.",
                    "Dr. Amara Nwosu", "AI researcher at the African Institute for Mathematical Sciences.",
                    70, 90, 2),
            new ProgSeed(0, 0, "Workshop: Building Scalable APIs with Spring Boot",
                    "Hands-on session — attendees build and deploy a production-ready REST API.",
                    "Tunde Babatunde", "Senior Backend Engineer at Flutterwave.",
                    180, 120, 3),
            new ProgSeed(0, 0, "Fireside Chat: From Idea to Series A",
                    "Three founders share candid lessons from raising their first institutional rounds.",
                    "Zainab Musa", "Investor and founding partner at Lagos Ventures.",
                    330, 60, 4),
            new ProgSeed(0, 0, "Closing: Networking Reception",
                    "Open networking with refreshments provided by our catering partner.",
                    null, null, 420, 60, 5),

            // AI & Machine Learning Summit (Akin, event 1)
            new ProgSeed(0, 1, "Welcome & State of AI in Nigeria",
                    "A data-driven overview of AI adoption across Nigerian industries.",
                    "Chidi Eze", "Head of Data Science at Access Bank.",
                    0, 45, 1),
            new ProgSeed(0, 1, "Deep Learning for Healthcare Diagnostics",
                    "Case study: using convolutional neural networks to detect malaria from microscopy images.",
                    "Prof. Ngozi Adeyemi", "Professor of Computational Biology, University of Lagos.",
                    55, 60, 2),
            new ProgSeed(0, 1, "Ethics & Bias in AI Systems",
                    "Understanding and mitigating bias when training on African datasets.",
                    "Fatima Al-Hassan", "AI Policy Researcher, Carnegie Mellon Africa.",
                    125, 45, 3),
            new ProgSeed(0, 1, "Live Demo: Building a Chatbot with LLMs",
                    "From zero to working chatbot — live coding session in Python.",
                    "Emeka Obi", "Staff ML Engineer, Google.",
                    180, 90, 4),

            // Afrobeats Night Out (Chioma, event 0)
            new ProgSeed(1, 0, "Doors Open & DJ Set",
                    "Welcome set from resident DJ spinning classic and contemporary Afrobeats.",
                    "DJ Kemi", "Lagos-based DJ and producer with 10+ years on the scene.",
                    0, 60, 1),
            new ProgSeed(1, 0, "Opening Act: Emerging Artists Showcase",
                    "Three up-and-coming acts get 20 minutes each to show what they've got.",
                    null, null, 60, 60, 2),
            new ProgSeed(1, 0, "Headline Performance",
                    "The evening's headline act takes the stage for a full 90-minute set.",
                    "Seun Kuti", "Afrobeat legend and son of the Afrobeat king Fela Kuti.",
                    150, 90, 3),

            // Entrepreneurs Summit 2026 (Emeka, event 0)
            new ProgSeed(2, 0, "Registration & Morning Coffee",
                    "Arrival, badge collection, and informal networking over coffee.",
                    null, null, -30, 30, 1),
            new ProgSeed(2, 0, "State of Entrepreneurship in Nigeria",
                    "Annual benchmarking report: funding, exits, and sector trends.",
                    "Bola Okonkwo", "CEO, Nigerian Startup Alliance.",
                    0, 50, 2),
            new ProgSeed(2, 0, "Panel: Access to Capital — Debt vs. Equity",
                    "Founders and investors debate the right financing mix at each growth stage.",
                    "Adaeze Nnamdi", "Partner, Ventures Platform.",
                    60, 75, 3),
            new ProgSeed(2, 0, "Masterclass: Building a Sales Engine from Scratch",
                    "Practical frameworks for early-stage B2B sales — pipeline, cadence, and closing.",
                    "Jide Afolabi", "VP Sales, Paystack.",
                    150, 60, 4),
            new ProgSeed(2, 0, "Pitch Competition: Top 5 Startups",
                    "Five finalists pitch to a live panel of investors for a ₦5M prize.",
                    null, null, 240, 90, 5),
            new ProgSeed(2, 0, "Awards & Networking Dinner",
                    "Entrepreneur of the Year awards followed by a sit-down dinner.",
                    null, null, 360, 120, 6),

            // SME Growth Conference (Emeka, event 1 — private)
            new ProgSeed(2, 1, "Welcome & Introductions",
                    "Brief introductions from each attendee — curated group of 40 SME owners.",
                    null, null, 0, 30, 1),
            new ProgSeed(2, 1, "Financial Management for SMEs",
                    "Understanding cash flow, credit, and working capital for small businesses.",
                    "Tosin Adesanya", "Chartered Accountant and SME Finance Advisor.",
                    30, 90, 2),
            new ProgSeed(2, 1, "Digital Marketing on a Budget",
                    "How to build a brand and acquire customers with ₦50k/month or less.",
                    "Bukola Adekunle", "Founder, Digital Bridge Agency.",
                    135, 60, 3),
            new ProgSeed(2, 1, "Open Q&A and Action Planning",
                    "Attendees workshop their own business challenges with expert guidance.",
                    null, null, 210, 75, 4),

            // Lagos Food & Wine Festival (Funke, event 0)
            new ProgSeed(3, 0, "Festival Opens — Culinary Village",
                    "Explore 30+ food stalls representing every region of Nigeria.",
                    null, null, 0, 120, 1),
            new ProgSeed(3, 0, "Chef Demo: Modern Nigerian Cuisine",
                    "Live cooking demonstration blending traditional recipes with global techniques.",
                    "Chef Sola Williams", "Executive Chef, Oriental Hotel Lagos.",
                    120, 60, 2),
            new ProgSeed(3, 0, "Wine Pairing Masterclass",
                    "Discovering Nigerian and international wines that complement West African cuisine.",
                    "Amaka Osei", "Certified Sommelier.",
                    200, 90, 3),
            new ProgSeed(3, 0, "Street Food Cook-Off Competition",
                    "Eight vendors compete for the People's Choice Award voted live by attendees.",
                    null, null, 300, 120, 4),

            // Nollywood Film Premiere (Ifeanyi, event 1 — private)
            new ProgSeed(6, 1, "Red Carpet Arrivals",
                    "Press and VIP guests arrive on the red carpet — photography and interviews.",
                    null, null, -60, 60, 1),
            new ProgSeed(6, 1, "Welcome Remarks from the Director",
                    "The director introduces the film, the cast, and the story behind the project.",
                    "Kunle Afolayan", "Acclaimed Nollywood director and producer.",
                    0, 15, 2),
            new ProgSeed(6, 1, "Film Screening",
                    "World premiere screening of the feature film.",
                    null, null, 15, 120, 3),
            new ProgSeed(6, 1, "Cast Q&A",
                    "The director and lead cast take questions from the audience.",
                    null, null, 145, 30, 4),
            new ProgSeed(6, 1, "After-Party",
                    "Cocktails and canapes — private reception for cast, crew, and invited guests.",
                    null, null, 185, 90, 5),

            // Women in STEM Conference (Halima, event 0)
            new ProgSeed(5, 0, "Opening Keynote: Why Representation Matters",
                    "Exploring the systemic barriers and the business case for diversity in STEM.",
                    "Dr. Aisha Umar", "Deputy Director General, NITDA.",
                    0, 50, 1),
            new ProgSeed(5, 0, "Workshop: Breaking into Big Tech",
                    "CV clinic, interview prep, and networking strategies for women in engineering.",
                    "Ngozi Akpan", "Senior SWE at Microsoft Africa.",
                    60, 90, 2),
            new ProgSeed(5, 0, "Panel: Navigating the Workplace as a Woman in STEM",
                    "Four senior leaders share stories, strategies, and hard-won advice.",
                    null, null, 165, 75, 3),
            new ProgSeed(5, 0, "Mentorship Speed Networking",
                    "30 mentors, 10 minutes each — structured mentorship matching session.",
                    null, null, 255, 90, 4),

            // Lagos Fashion Week (Lara, event 0)
            new ProgSeed(9, 0, "Doors Open & Cocktail Reception",
                    "Welcome reception in the foyer — champagne and canapés.",
                    null, null, -30, 30, 1),
            new ProgSeed(9, 0, "Opening Collection: Heritage Reborn",
                    "Lara Williams' signature collection inspired by Yoruba textile traditions.",
                    null, null, 0, 45, 2),
            new ProgSeed(9, 0, "Guest Designer: Contemporary African Streetwear",
                    "Lagos-based streetwear label Àṣà presents their debut runway collection.",
                    null, null, 55, 40, 3),
            new ProgSeed(9, 0, "Headline Show: Futurewear 2030",
                    "The festival's headline show — 10 designers, one cohesive vision.",
                    null, null, 110, 75, 4),
            new ProgSeed(9, 0, "Closing & Press Interviews",
                    "Press access for interviews with participating designers.",
                    null, null, 195, 45, 5),

            // Digital Marketing Summit 2026 (Musa, event 0)
            new ProgSeed(10, 0, "Welcome & State of Digital Marketing",
                    "An overview of digital marketing trends in Nigeria and across Africa.",
                    "Musa Ibrahim", "Head of Growth, Jumia Nigeria.",
                    0, 45, 1),
            new ProgSeed(10, 0, "Masterclass: SEO & Content Strategy",
                    "Proven tactics for ranking higher and driving organic traffic.",
                    "Tobi Fashola", "SEO Lead, Paystack.",
                    55, 75, 2),
            new ProgSeed(10, 0, "Panel: Social Media ROI — Myth or Reality?",
                    "Marketers debate metrics, attribution, and what actually drives conversions.",
                    "Amaka Chukwu", "Digital Marketing Director, MTN Nigeria.",
                    140, 60, 3),
            new ProgSeed(10, 0, "Workshop: Google Ads & Meta for SMEs",
                    "Hands-on ad creation and targeting — bring your business, leave with a live campaign.",
                    "Chuka Nwosu", "Certified Google Partner & Trainer.",
                    210, 90, 4),
            new ProgSeed(10, 0, "Networking & Cocktail Hour",
                    "Open networking for attendees and speakers.",
                    null, null, 330, 60, 5),

            // Growth Hacking Workshop (Musa, event 1)
            new ProgSeed(10, 1, "The Growth Hacking Mindset",
                    "Why traditional marketing fails startups and what to do instead.",
                    "Seun Akerele", "Growth Lead, Flutterwave.",
                    0, 50, 1),
            new ProgSeed(10, 1, "Viral Loops & Referral Programs",
                    "Designing growth loops that compound — case studies from Piggyvest and Cowrywise.",
                    "Ngozi Eze", "Product Growth Manager, PiggyVest.",
                    60, 60, 2),
            new ProgSeed(10, 1, "Live Hacking Session",
                    "Teams compete to design a growth strategy for a fictional startup in 45 minutes.",
                    null, null, 130, 90, 3),

            // Media Production Conference (Ngozi, event 0)
            new ProgSeed(11, 0, "Opening: The Future of African Media",
                    "How Nigeria's media industry is evolving in the streaming age.",
                    "Ngozi Okonkwo", "CEO, MultiChoice Nigeria.",
                    0, 50, 1),
            new ProgSeed(11, 0, "Panel: Monetising Content in Nigeria",
                    "YouTube, TikTok, Podcasts — where creators are making real money.",
                    "Korty EO", "Award-winning documentary filmmaker.",
                    60, 75, 2),
            new ProgSeed(11, 0, "Workshop: Broadcast Production on a Budget",
                    "Practical techniques for professional-quality video with minimal equipment.",
                    "Chidi Okeke", "Production Director, Channels TV.",
                    145, 90, 3),
            new ProgSeed(11, 0, "Screening: Best of Nigerian Indie Film 2026",
                    "Curated short films and documentaries from emerging Nigerian filmmakers.",
                    null, null, 245, 75, 4),

            // Podcast & Audio Summit (Ngozi, event 1)
            new ProgSeed(11, 1, "The Audio Revolution in Africa",
                    "Why podcasting is exploding and what it means for brands and creators.",
                    "Kunle Soname", "Host, The Business Day Podcast.",
                    0, 45, 1),
            new ProgSeed(11, 1, "Monetise Your Podcast",
                    "Sponsorships, Patreon, and premium content — realistic paths to revenue.",
                    "Adaeze Nnaji", "Top 10 Nigerian Podcast Host.",
                    55, 60, 2),
            new ProgSeed(11, 1, "Live Recording Demo & Q&A",
                    "Experience a live podcast recording and ask the experts anything.",
                    null, null, 125, 75, 3),

            // Holistic Health Expo 2026 (Oluwatoyin, event 0)
            new ProgSeed(12, 0, "Opening: Holistic Health — A Nigerian Perspective",
                    "Integrating traditional and modern approaches to well-being.",
                    "Dr. Yetunde Obe", "Consultant Physician & Wellness Advocate.",
                    0, 45, 1),
            new ProgSeed(12, 0, "Workshop: Stress Management for Busy Professionals",
                    "Evidence-based tools for managing stress, anxiety, and burnout.",
                    "Chinyere Obi", "Clinical Psychologist.",
                    55, 60, 2),
            new ProgSeed(12, 0, "Panel: Mental Health, Nutrition & Movement",
                    "Experts discuss the interconnected pillars of holistic health.",
                    "Dr. Babatunde Adeyemi", "Sports Medicine Specialist.",
                    125, 75, 3),
            new ProgSeed(12, 0, "Live Yoga & Breathwork Session",
                    "Guided 30-minute session — mats provided for the first 200 attendees.",
                    "Adaora Bello", "Certified Yoga Instructor.",
                    210, 45, 4),
            new ProgSeed(12, 0, "Exhibition & Product Demos",
                    "Explore wellness brands, supplements, and fitness equipment.",
                    null, null, 270, 90, 5),

            // Fitness Challenge Series (Oluwatoyin, event 1)
            new ProgSeed(12, 1, "Kick-Off: 12 Weeks to a Better You",
                    "Programme overview, goal setting, and team formation.",
                    "Coach Olusegun Bello", "NSCA Certified Strength Coach.",
                    0, 50, 1),
            new ProgSeed(12, 1, "Movement Assessment & Baseline Testing",
                    "Participants undergo fitness tests to establish starting benchmarks.",
                    null, null, 60, 90, 2),

            // Contemporary Art Exhibition (Precious, event 0)
            new ProgSeed(13, 0, "Exhibition Opens — Curator's Welcome",
                    "The curator introduces the 20 featured artists and the exhibition theme.",
                    "Precious Nwankwo", "Curator & Founder, Lagos Art Collective.",
                    0, 30, 1),
            new ProgSeed(13, 0, "Artist Talk: Process & Inspiration",
                    "Three featured artists discuss their creative journeys.",
                    "Tunde Afolabi", "Mixed-media artist.",
                    40, 60, 2),
            new ProgSeed(13, 0, "Live Painting Performance",
                    "Watch an artist create a large-format piece in real time.",
                    "Emeka Uche", "Live performance artist.",
                    110, 45, 3),
            new ProgSeed(13, 0, "Collectors' Q&A & Private Viewing",
                    "Guided walkthrough for collectors — acquisition enquiries welcome.",
                    null, null, 165, 60, 4),

            // Sculpture & Installation Art (Precious, event 1)
            new ProgSeed(13, 1, "Opening Remarks & Exhibition Walkthrough",
                    "Curator-led tour of the 15-piece sculpture and installation collection.",
                    "Dr. Amara Okafor", "Art Historian, University of Lagos.",
                    0, 45, 1),
            new ProgSeed(13, 1, "Panel: The Market for Contemporary African Sculpture",
                    "Collectors, gallery owners, and artists discuss valuation and demand.",
                    null, null, 55, 60, 2),

            // Supply Chain Optimization Forum (Rasheed, event 0)
            new ProgSeed(14, 0, "Keynote: Nigeria's Logistics Landscape 2026",
                    "An honest assessment of infrastructure gaps and emerging solutions.",
                    "Rasheed Yusuf", "CEO, SwiftMoves Logistics.",
                    0, 50, 1),
            new ProgSeed(14, 0, "Panel: Last-Mile Delivery — Solving the Final Challenge",
                    "How companies are cracking same-day and next-day delivery in Lagos.",
                    "Amina Suleiman", "COO, Kwik Delivery.",
                    60, 75, 2),
            new ProgSeed(14, 0, "Workshop: Warehouse Layout & Inventory Optimization",
                    "Practical layout design and inventory management for SME warehouses.",
                    "Engr. Oluwafemi Ade", "Industrial Engineer, DHL Nigeria.",
                    145, 90, 3),
            new ProgSeed(14, 0, "Tech Demo: TMS & WMS Platforms for Growing Businesses",
                    "Live demos of transport management and warehouse systems.",
                    null, null, 245, 60, 4),

            // Warehouse Management Summit (Rasheed, event 1)
            new ProgSeed(14, 1, "State of Warehousing in Nigeria",
                    "Data on storage capacity, occupancy, and forecast demand.",
                    "Dr. Kunle Lawal", "Economist, Lagos Chamber of Commerce.",
                    0, 45, 1),
            new ProgSeed(14, 1, "Cold Chain & Perishables Management",
                    "Maintaining product integrity from farm to final mile.",
                    "Bisi Ogunbamowo", "Cold Chain Manager, PZ Cussons.",
                    55, 60, 2),

            // Web3 & Blockchain Summit (Seun, event 0)
            new ProgSeed(15, 0, "Opening: The State of Web3 in Africa",
                    "Africa's blockchain ecosystem — adoption, challenges, and potential.",
                    "Seun Akanji", "Blockchain Researcher & Founder, ChainAfrica.",
                    0, 50, 1),
            new ProgSeed(15, 0, "Workshop: Building Your First dApp on Ethereum",
                    "Hands-on development workshop — Solidity basics to a deployed smart contract.",
                    "Chukwuemeka Obi", "Lead Smart Contract Developer, Binance Africa.",
                    60, 120, 2),
            new ProgSeed(15, 0, "Panel: DeFi — Opportunity or Trap?",
                    "Investors, developers, and regulators debate decentralised finance in Nigeria.",
                    "Kola Adedeji", "Director, SEC Nigeria Digital Assets Division.",
                    190, 75, 3),
            new ProgSeed(15, 0, "NFT & Digital Ownership for African Creators",
                    "How artists, musicians, and filmmakers are monetising through NFTs.",
                    "DJ Neptune", "Afrobeats artist and NFT pioneer.",
                    275, 60, 4),

            // Cloud Architecture Masterclass (Seun, event 1)
            new ProgSeed(15, 1, "Cloud-Native Design Principles",
                    "12-factor apps, microservices, and designing for resilience.",
                    "Taiwo Adeyemi", "Principal Cloud Architect, AWS Africa.",
                    0, 75, 1),
            new ProgSeed(15, 1, "Hands-On: Deploying a Scalable API on AWS",
                    "Build and deploy a production-grade REST API from scratch.",
                    "Folake Bello", "Senior DevOps Engineer, Interswitch.",
                    85, 90, 2),
            new ProgSeed(15, 1, "Cost Optimisation & FinOps Best Practices",
                    "Reduce your cloud bill without sacrificing performance.",
                    null, null, 185, 60, 3),

            // Investment Summit 2026 (Tunde, event 0)
            new ProgSeed(16, 0, "Opening: The Investment Climate in Nigeria 2026",
                    "Macroeconomic overview and what it means for individual and institutional investors.",
                    "Tunde Okafor", "Chief Investment Officer, Stanbic IBTC.",
                    0, 50, 1),
            new ProgSeed(16, 0, "Panel: Fixed Income vs. Equities — Where to Put Your Money",
                    "Portfolio managers debate asset allocation in a high-inflation environment.",
                    "Nkechi Osei", "MD, Chapel Hill Denham.",
                    60, 75, 2),
            new ProgSeed(16, 0, "Masterclass: Building a ₦10M Portfolio from Scratch",
                    "Step-by-step framework for new retail investors.",
                    "Ayo Martins", "Certified Financial Planner.",
                    145, 90, 3),
            new ProgSeed(16, 0, "Demo: Using Nigerian Fintech Apps for Investing",
                    "Live demos of Bamboo, Trove, and Risevest.",
                    null, null, 245, 60, 4),

            // Cryptocurrency & Digital Assets (Tunde, event 1)
            new ProgSeed(16, 1, "Crypto 101 for Nigerian Investors",
                    "What is crypto, how does it work, and is it legal in Nigeria?",
                    "Bolu Adesina", "Crypto Analyst & Educator.",
                    0, 45, 1),
            new ProgSeed(16, 1, "Technical Analysis & Trading Strategies",
                    "Reading charts, identifying patterns, and managing risk.",
                    "Segun Olatunji", "Professional Crypto Trader.",
                    55, 75, 2),
            new ProgSeed(16, 1, "Panel: Stablecoins & Cross-Border Payments",
                    "How USDT and USDC are transforming remittances for Nigerians.",
                    null, null, 140, 60, 3),

            // Community Leadership Forum (Uche, event 0)
            new ProgSeed(17, 0, "Opening: Community Power in the Digital Age",
                    "How technology is amplifying grassroots community action.",
                    "Uche Anyanwu", "Executive Director, Lagos Community Foundation.",
                    0, 45, 1),
            new ProgSeed(17, 0, "Panel: Bridging the Urban-Rural Development Gap",
                    "Leaders from Lagos, Kano, and Enugu share contrasting realities.",
                    "Mallam Bello Umar", "Local Government Chairman, Nassarawa LGA.",
                    55, 75, 2),
            new ProgSeed(17, 0, "Workshop: Designing Community Projects That Stick",
                    "Frameworks for sustainable community initiatives with limited budgets.",
                    "Dr. Adunola Ogunfemi", "Community Development Consultant.",
                    140, 90, 3),

            // Social Impact Workshop (Uche, event 1)
            new ProgSeed(17, 1, "Theory of Change — Making Your Idea Actionable",
                    "Turn vague social goals into measurable, funded programmes.",
                    "Emeka Nwosu", "Director of Programmes, Tony Elumelu Foundation.",
                    0, 60, 1),
            new ProgSeed(17, 1, "Funding Your Impact: Grants, CSR & Crowdfunding",
                    "Practical guide to accessing funds for social enterprises.",
                    "Chinwe Okoye", "Grants Consultant.",
                    70, 75, 2),

            // African Culture Festival (Vicky, event 0)
            new ProgSeed(18, 0, "Grand Opening Procession",
                    "Cultural performers from 10 Nigerian states open the festival.",
                    null, null, 0, 45, 1),
            new ProgSeed(18, 0, "Heritage Village Walkthrough",
                    "Explore 12 cultural booths showcasing food, craft, and tradition.",
                    "Vicky Osei", "Festival Director & Cultural Anthropologist.",
                    45, 120, 2),
            new ProgSeed(18, 0, "Panel: Preserving African Culture in a Globalised World",
                    "How do we keep traditions alive while embracing modernity?",
                    "Prof. Bisi Fayemi", "Dept. of African Studies, UNILAG.",
                    175, 75, 3),
            new ProgSeed(18, 0, "Evening Performances — Music & Dance",
                    "Live performances by traditional and contemporary musicians.",
                    null, null, 270, 120, 4),

            // Traditional Music & Dance (Vicky, event 1)
            new ProgSeed(18, 1, "Opening: The Rhythm of Africa",
                    "Introduction to West African percussion traditions.",
                    "Baba Seun", "Master Drummer, Egungun Society.",
                    0, 30, 1),
            new ProgSeed(18, 1, "Dance Workshop — Bata, Swange & Atilogwu",
                    "Hands-on dance sessions with instructors from three Nigerian traditions.",
                    null, null, 40, 90, 2),
            new ProgSeed(18, 1, "Fusion Performance: Traditional Meets Contemporary",
                    "Watch musicians and dancers blend ancestral forms with modern expression.",
                    null, null, 140, 60, 3),

            // Innovation Expo 2026 (Wuraola, event 0)
            new ProgSeed(19, 0, "Opening Keynote: The Nigerian Innovation Decade",
                    "Why the next wave of global innovation will be shaped by Africa.",
                    "Wuraola Lawal", "Chief Innovation Officer, Guaranty Trust Bank.",
                    0, 50, 1),
            new ProgSeed(19, 0, "Start-up Pavilion Pitch Sessions",
                    "20 start-ups get 5 minutes each to demo their solutions to live investors.",
                    null, null, 60, 120, 2),
            new ProgSeed(19, 0, "Deep Dive: AgriTech & FoodTech in Nigeria",
                    "How technology is transforming food production and distribution.",
                    "Ngozi Adaeze", "CEO, FarmCrowdy.",
                    190, 60, 3),
            new ProgSeed(19, 0, "Demo Zone: Robotics, AI & IoT",
                    "Interactive demos from Nigeria's leading hardware and AI start-ups.",
                    null, null, 260, 90, 4),
            new ProgSeed(19, 0, "Awards: Most Innovative Startup 2026",
                    "Investor panel announces this year's winners across five categories.",
                    null, null, 370, 45, 5),

            // Deep Tech Bootcamp (Wuraola, event 1)
            new ProgSeed(19, 1, "Introduction to Deep Tech Sectors",
                    "AI, biotech, clean energy, advanced manufacturing — primer for beginners.",
                    "Dr. Kunle Afolabi", "Research Lead, Google DeepMind Africa.",
                    0, 60, 1),
            new ProgSeed(19, 1, "Problem-Solution Sprint",
                    "Teams identify a deep-tech solvable problem and prototype a solution concept.",
                    null, null, 70, 180, 2),
            new ProgSeed(19, 1, "Demo Day: Present Your Concept",
                    "Each team presents to a panel of deep-tech investors.",
                    null, null, 270, 90, 3),

            // Annual Entrepreneurs Summit (Xolani, event 0)
            new ProgSeed(20, 0, "Opening: The State of African Entrepreneurship",
                    "Data and stories from the 2025 African Startup Ecosystem Report.",
                    "Xolani Zuma", "Executive Director, African Business Council.",
                    0, 50, 1),
            new ProgSeed(20, 0, "Fireside Chat: From ₦50k to ₦50M",
                    "An honest conversation about the grinding early years of building a business.",
                    "Temitayo Ogunlesi", "Founder, Ogunlesi Holdings.",
                    60, 60, 2),
            new ProgSeed(20, 0, "Workshop: Systemising Your Business for Scale",
                    "SOPs, delegation, and the tools that free you to lead.",
                    "Busola Akin", "Business Systems Consultant.",
                    130, 90, 3),
            new ProgSeed(20, 0, "Investor Panel: What We Look for in 2026",
                    "Four VCs share what they're funding — and what they're passing on.",
                    null, null, 230, 75, 4),
            new ProgSeed(20, 0, "Networking Dinner",
                    "Sit-down dinner with curated table assignments for maximum networking.",
                    null, null, 330, 120, 5),

            // Pre-Launch Bootcamp (Xolani, event 1)
            new ProgSeed(20, 1, "Market Validation Masterclass",
                    "How to know if your idea is worth building before spending a naira.",
                    "Chidi Mmadu", "Lean Startup Facilitator.",
                    0, 75, 1),
            new ProgSeed(20, 1, "Building an MVP in 3 Weeks",
                    "No-code and low-code tools for rapid prototyping.",
                    "Ada Oguike", "Product Designer, Paystack.",
                    85, 90, 2),
            new ProgSeed(20, 1, "Your First 100 Customers",
                    "Guerrilla marketing and direct sales tactics for pre-launch growth.",
                    null, null, 185, 60, 3),

            // Major Trade Expo 2026 (Yetunde, event 0)
            new ProgSeed(21, 0, "Exhibition Hall Opens",
                    "Over 200 exhibitors across FMCG, manufacturing, agribusiness, and services.",
                    null, null, 0, 30, 1),
            new ProgSeed(21, 0, "Keynote: Intra-Africa Trade & AfCFTA Opportunities",
                    "Unlocking the ₦40 trillion African free trade opportunity.",
                    "Dr. Titi Alabi", "AfCFTA Advisor, Nigerian Government.",
                    40, 50, 2),
            new ProgSeed(21, 0, "B2B Matchmaking Sessions",
                    "Pre-scheduled 20-minute meetings between buyers and suppliers.",
                    null, null, 100, 240, 3),
            new ProgSeed(21, 0, "Panel: E-commerce & the Future of Retail",
                    "How online marketplaces are transforming the Nigerian retail landscape.",
                    "Juliet Anammah", "Former CEO, Jumia Nigeria.",
                    360, 75, 4),

            // Consumer Products Showcase (Yetunde, event 1)
            new ProgSeed(21, 1, "New Product Launch Showcase",
                    "30 brands launch new products in 5-minute live presentations.",
                    null, null, 0, 180, 1),
            new ProgSeed(21, 1, "Consumer Insights Panel",
                    "What Nigerian consumers want in 2026 — live research reveal.",
                    "Adaeze Obi", "Market Research Director, Nielsen Nigeria.",
                    190, 60, 2),

            // Annual Business Conference (Zainab, event 0)
            new ProgSeed(22, 0, "Opening Keynote: Leadership in Uncertainty",
                    "Navigating business disruptions with clarity and conviction.",
                    "Zainab Hassan", "MD, First Bank of Nigeria.",
                    0, 50, 1),
            new ProgSeed(22, 0, "Panel: Corporate Governance & Accountability",
                    "Board members, regulators, and executives on best governance practices.",
                    "Justice Kalu Anyim", "Former Chief Justice.",
                    60, 75, 2),
            new ProgSeed(22, 0, "Workshop: Managing High-Performance Teams",
                    "Tools and frameworks for leaders of growing organisations.",
                    "Femi Ade", "Organizational Psychologist.",
                    145, 90, 3),
            new ProgSeed(22, 0, "Closing: Awards for Business Excellence 2026",
                    "Recognising outstanding organisations across five sectors.",
                    null, null, 255, 60, 4),

            // Leadership Development Program (Zainab, event 1)
            new ProgSeed(22, 1, "Servant Leadership — Principles & Practice",
                    "Leading with empathy, humility, and purpose.",
                    "Rev. Tunde Bakare", "Pastor & Civic Leader.",
                    0, 60, 1),
            new ProgSeed(22, 1, "360° Feedback Exercise",
                    "Structured peer-feedback process with facilitated debrief.",
                    null, null, 70, 75, 2),

            // Skills Development Bootcamp (Amara, event 0)
            new ProgSeed(23, 0, "Welcome & Skills Audit",
                    "Participants assess their current skills and set personal development goals.",
                    null, null, 0, 45, 1),
            new ProgSeed(23, 0, "Communication & Presentation Skills",
                    "Practical exercises in public speaking, storytelling, and persuasion.",
                    "Amara Okafor", "Corporate Trainer & Coach.",
                    55, 90, 2),
            new ProgSeed(23, 0, "Critical Thinking & Problem Solving",
                    "Tools for structured analysis and decision-making under pressure.",
                    "Dr. Chinyere Uche", "Executive Coach.",
                    155, 75, 3),
            new ProgSeed(23, 0, "Technology Skills for the Modern Workplace",
                    "Excel, AI tools, and digital collaboration platforms.",
                    "Tayo Fashola", "Digital Transformation Lead.",
                    240, 90, 4),

            // Leadership Coaching Program (Amara, event 1)
            new ProgSeed(23, 1, "Self-Assessment: Your Leadership Style",
                    "Diagnostic questionnaire with facilitated debrief.",
                    null, null, 0, 60, 1),
            new ProgSeed(23, 1, "Coaching Fundamentals — Give & Receive Feedback",
                    "How to coach your team members and receive coaching gracefully.",
                    "Bukola Adetunji", "ICF Certified Coach.",
                    70, 90, 2),

            // Annual Business Leaders Forum (Bolaji, event 0)
            new ProgSeed(24, 0, "State of Nigerian Business 2026",
                    "Annual survey results: business confidence, talent, and technology.",
                    "Bolaji Oni", "Chairman, Lagos Chamber of Commerce.",
                    0, 50, 1),
            new ProgSeed(24, 0, "Panel: Accessing Growth Capital in a Tight Market",
                    "Banks, DFIs, and VCs on funding options for established businesses.",
                    "Funmi Ogunbiyi", "MD, Bank of Industry.",
                    60, 75, 2),
            new ProgSeed(24, 0, "Masterclass: Scaling Across Multiple Markets",
                    "Case study on expanding from Lagos to Kano, Abuja, and internationally.",
                    "Kemi Lala Akindoju", "Serial Entrepreneur.",
                    145, 90, 3),
            new ProgSeed(24, 0, "Networking Luncheon",
                    "Hosted lunch with roundtable discussions on key business themes.",
                    null, null, 260, 90, 4),

            // Corporate Governance Summit (Bolaji, event 1)
            new ProgSeed(24, 1, "Keynote: Why Good Governance is Good Business",
                    "Evidence from companies that thrive long-term through ethical governance.",
                    "Prof. Pat Utomi", "Economist & Governance Expert.",
                    0, 50, 1),
            new ProgSeed(24, 1, "Workshop: Structuring Your Board for Growth",
                    "Who to put on your board and how to run effective board meetings.",
                    "Abimbola Cole", "Corporate Lawyer.",
                    60, 90, 2),

            // Annual Celebration Festival (Chidinma, event 0)
            new ProgSeed(25, 0, "Festival Opening Ceremony",
                    "Cultural welcome, traditional blessing, and official launch.",
                    "Chidinma Obi", "Festival Founder & Cultural Director.",
                    0, 30, 1),
            new ProgSeed(25, 0, "Food Village: Taste of Nigeria",
                    "50+ food vendors representing every geopolitical zone of Nigeria.",
                    null, null, 30, 180, 2),
            new ProgSeed(25, 0, "Main Stage: Live Music Performances",
                    "Performances by afrobeats, fuji, and highlife artists.",
                    null, null, 240, 120, 3),
            new ProgSeed(25, 0, "Grand Finale: Fireworks & Closing Concert",
                    "An unforgettable close to a day of celebration.",
                    null, null, 420, 60, 4),

            // Cultural Food Festival (Chidinma, event 1)
            new ProgSeed(25, 1, "Cooking Demonstration: Dishes from Every State",
                    "Celebrity chefs prepare signature dishes from all 36 Nigerian states.",
                    "Chef Zara Abubakar", "Head Chef & Culinary Ambassador.",
                    0, 90, 1),
            new ProgSeed(25, 1, "Food Photography Masterclass",
                    "How to capture food beautifully for social media and menus.",
                    "Tobi Taiwo", "Food Photographer.",
                    100, 60, 2),

            // Annual Wellness Retreat (Daniel, event 0)
            new ProgSeed(26, 0, "Arrival, Check-In & Welcome Circle",
                    "Grounding session to transition from city pace to retreat mode.",
                    "Daniel Ibekwe", "Retreat Facilitator.",
                    0, 45, 1),
            new ProgSeed(26, 0, "Morning: Nature Walk & Silent Reflection",
                    "Guided 2-hour walk through nature with optional journaling.",
                    null, null, 55, 120, 2),
            new ProgSeed(26, 0, "Workshop: Digital Detox & Reconnecting with Self",
                    "Guided exercises for intentional disconnection and presence.",
                    "Dr. Ngozi Fashakin", "Mindfulness Therapist.",
                    195, 75, 3),

            // Mindfulness & Meditation Workshop (Daniel, event 1)
            new ProgSeed(26, 1, "Introduction to Mindfulness",
                    "The science and practice of mindfulness for modern professionals.",
                    "Daniel Ibekwe", "Certified MBSR Instructor.",
                    0, 60, 1),
            new ProgSeed(26, 1, "Guided Meditation Series",
                    "Body scan, breath awareness, and loving-kindness meditation.",
                    null, null, 70, 90, 2),
            new ProgSeed(26, 1, "Mindful Communication Workshop",
                    "Applying mindfulness to listening, speaking, and relationships.",
                    "Amaka Osei", "Communication Coach.",
                    170, 75, 3),

            // Annual Charity Gala Dinner (Ebube, event 0)
            new ProgSeed(27, 0, "Cocktail Reception",
                    "Welcome drinks and canapes as guests arrive.",
                    null, null, -30, 30, 1),
            new ProgSeed(27, 0, "Opening Remarks & Charity Spotlight",
                    "Hear directly from the beneficiaries of this year's charity.",
                    "Ebube Eze", "Gala Host & Philanthropist.",
                    0, 20, 2),
            new ProgSeed(27, 0, "Three-Course Dinner",
                    "Fine dining prepared by Executive Chef.",
                    null, null, 25, 90, 3),
            new ProgSeed(27, 0, "Keynote: The Business Case for Giving",
                    "Why CSR and philanthropy drive long-term business performance.",
                    "Tony Elumelu", "Chairman, United Bank for Africa.",
                    120, 40, 4),
            new ProgSeed(27, 0, "Charity Auction & Fund-Raising",
                    "Live auction of art, experiences, and exclusive packages.",
                    null, null, 165, 75, 5),

            // Awards & Recognition Gala (Ebube, event 1)
            new ProgSeed(27, 1, "Red Carpet Arrival",
                    "Guests arrive and are photographed on the red carpet.",
                    null, null, -30, 30, 1),
            new ProgSeed(27, 1, "Opening Performance",
                    "A spectacular musical performance opens the awards ceremony.",
                    null, null, 0, 20, 2),
            new ProgSeed(27, 1, "Awards Ceremony: Industry Excellence",
                    "20 awards across categories including Innovation, Leadership, and Impact.",
                    null, null, 25, 150, 3),

            // Annual Research Symposium (Folake, event 0)
            new ProgSeed(28, 0, "Opening Plenary: Frontiers of Nigerian Research",
                    "A survey of breakthrough research coming out of Nigerian institutions.",
                    "Prof. Folake Adekunle", "Dean of Research, UNILAG.",
                    0, 50, 1),
            new ProgSeed(28, 0, "Paper Presentations: Track A — STEM",
                    "Six 15-minute research paper presentations followed by Q&A.",
                    null, null, 60, 120, 2),
            new ProgSeed(28, 0, "Paper Presentations: Track B — Social Sciences",
                    "Six 15-minute research paper presentations followed by Q&A.",
                    null, null, 60, 120, 3),
            new ProgSeed(28, 0, "Poster Session & Exhibition",
                    "Researchers present findings at their poster displays.",
                    null, null, 200, 90, 4),
            new ProgSeed(28, 0, "Closing: Best Paper Awards",
                    "Prize giving for the top papers across all tracks.",
                    null, null, 310, 45, 5),

            // Academic Excellence Forum (Folake, event 1)
            new ProgSeed(28, 1, "Keynote: What Does Excellence Look Like in Nigeria?",
                    "Redefining academic success in the African context.",
                    "Dr. Ngozi Okonkwo", "Vice-Chancellor, Covenant University.",
                    0, 50, 1),
            new ProgSeed(28, 1, "Student Showcase: Most Impactful Research Projects",
                    "Five student teams present their research to the audience.",
                    null, null, 60, 90, 2),

            // Annual Street Carnival (Gbemi, event 0)
            new ProgSeed(29, 0, "Carnival Procession Opens",
                    "Floats, masquerades, and performers parade through the streets.",
                    "Gbemi Kolade", "Carnival Director.",
                    0, 60, 1),
            new ProgSeed(29, 0, "Main Stage: DJ Sets & Live Music",
                    "Non-stop music from Nigeria's hottest DJs.",
                    null, null, 60, 180, 2),
            new ProgSeed(29, 0, "Carnival Games & Activities Zone",
                    "Competitions, prizes, and interactive fun for all ages.",
                    null, null, 60, 300, 3),
            new ProgSeed(29, 0, "Evening Headline Concert",
                    "Three headline acts close out the carnival.",
                    null, null, 360, 120, 4),

            // Entertainment & Comedy Fest (Gbemi, event 1)
            new ProgSeed(29, 1, "Opening: Warm-Up Comedy Sets",
                    "Emerging comedians get 10 minutes each to warm up the crowd.",
                    null, null, 0, 60, 1),
            new ProgSeed(29, 1, "Headline Comedy Show",
                    "Nigeria's top three comedians perform back-to-back.",
                    "MC Basketmouth", "Nigeria's biggest stand-up comedian.",
                    70, 120, 2),
            new ProgSeed(29, 1, "Music & Comedy Fusion Finale",
                    "Live music and comedy sketches close the show.",
                    null, null, 200, 60, 3),

            // Annual Excellence Awards (Habiba, event 0)
            new ProgSeed(30, 0, "Welcome & Opening Remarks",
                    "Setting the tone for an evening of recognition and celebration.",
                    "Habiba Musa", "Awards Chair.",
                    0, 20, 1),
            new ProgSeed(30, 0, "Category Awards: Innovation & Technology",
                    "Recognising organisations driving innovation across Nigeria.",
                    null, null, 25, 45, 2),
            new ProgSeed(30, 0, "Category Awards: Social Impact & Sustainability",
                    "Honouring those making a difference beyond profit.",
                    null, null, 75, 45, 3),
            new ProgSeed(30, 0, "Keynote: The Responsibility of Excellence",
                    "A challenge to awardees to use their recognition to inspire others.",
                    "Prof. Wole Soyinka", "Nobel Laureate.",
                    130, 30, 4),
            new ProgSeed(30, 0, "Gala Dinner & Networking",
                    "Celebratory dinner following the awards ceremony.",
                    null, null, 175, 90, 5),

            // Industry Innovation Awards (Habiba, event 1)
            new ProgSeed(30, 1, "Finalists Showcase",
                    "Each finalist presents their innovation in 3 minutes.",
                    null, null, 0, 90, 1),
            new ProgSeed(30, 1, "Judges' Deliberation & Networking Break",
                    "Attendees network while judges deliberate.",
                    null, null, 100, 30, 2),
            new ProgSeed(30, 1, "Award Announcement & Keynote",
                    "Winners announced and a keynote address by the guest speaker.",
                    "Dr. Adesola Adeduntan", "CEO, First Bank.",
                    135, 60, 3),

            // Product Launch Showcase (Ibrahim, event 0)
            new ProgSeed(31, 0, "Opening: Why Nigeria Needs Local Innovation",
                    "The case for Nigerian-made products in a post-import-dependent economy.",
                    "Ibrahim Ahmed", "Founder, MadeInNigeria Initiative.",
                    0, 30, 1),
            new ProgSeed(31, 0, "Product Demonstrations: Consumer Tech",
                    "Six consumer technology products launch with live demos.",
                    null, null, 40, 90, 2),
            new ProgSeed(31, 0, "Product Demonstrations: FMCG & Lifestyle",
                    "Eight FMCG and lifestyle brands unveil new products.",
                    null, null, 140, 90, 3),
            new ProgSeed(31, 0, "Investor & Buyer Matching Session",
                    "Connect with investors and bulk buyers in structured 10-minute meetings.",
                    null, null, 240, 90, 4),
            new ProgSeed(31, 0, "Best New Product Awards",
                    "Audience votes for their favourite product across four categories.",
                    null, null, 345, 45, 5),

            // Live Demo & Presentation Event (Ibrahim, event 1)
            new ProgSeed(31, 1, "The Art of the Demo",
                    "How to demonstrate your product in a way that converts.",
                    "Tunde Fadahunsi", "Sales Coach.",
                    0, 45, 1),
            new ProgSeed(31, 1, "Hands-On Demo Stations",
                    "Attendees interact directly with products at 10 demo stations.",
                    null, null, 55, 90, 2),
            new ProgSeed(31, 1, "Fireside Chat: From Demo to ₦1B Revenue",
                    "How a great product demo launched a business.",
                    "Seun Osewa", "Founder, Nairaland.",
                    155, 60, 3),

            // DreamDev Test Demo (Semicolon, event 0) — Group 1–9 presentations
            new ProgSeed(32, 0, "Opening Ceremony",
                    "Welcome address from the Semicolon leadership team and introduction of the DreamDev cohort.",
                    "Blessing Abeng", "CEO, Semicolon Africa.",
                    0, 20, 1),
            new ProgSeed(32, 0, "Group 1 Presentation",
                    "Group 1 presents their capstone project — a full-stack expense tracking application built with Spring Boot and React.",
                    null, null, 20, 50, 2),
            new ProgSeed(32, 0, "Group 2 Presentation",
                    "Group 2 showcases a real-time logistics and delivery tracking platform with live map integration.",
                    null, null, 70, 50, 3),
            new ProgSeed(32, 0, "Group 3 Presentation",
                    "Group 3 demonstrates an AI-powered job-matching platform tailored for the Nigerian tech market.",
                    null, null, 120, 50, 4),
            new ProgSeed(32, 0, "Group 4 Presentation",
                    "Group 4 unveils a mobile-first health appointment booking system for community clinics.",
                    null, null, 170, 50, 5),
            new ProgSeed(32, 0, "Lunch Break",
                    "Break for lunch. Networking opportunity for attendees and cohort members.",
                    null, null, 220, 20, 6),
            new ProgSeed(32, 0, "Group 5 Presentation",
                    "Group 5 presents a multi-vendor e-commerce marketplace with escrow and dispute resolution.",
                    null, null, 240, 50, 7),
            new ProgSeed(32, 0, "Group 6 Presentation",
                    "Group 6 demonstrates a smart classroom management tool with automated attendance tracking.",
                    null, null, 290, 50, 8),
            new ProgSeed(32, 0, "Group 7 Presentation",
                    "Group 7 showcases a blockchain-based certificate verification system for Nigerian universities.",
                    null, null, 340, 50, 9),
            new ProgSeed(32, 0, "Group 8 Presentation",
                    "Group 8 presents a community events and ticketing platform for local organisers.",
                    null, null, 390, 50, 10),
            new ProgSeed(32, 0, "Group 9 Presentation",
                    "Group 9 unveils a conversational AI assistant for small business customer support.",
                    null, null, 440, 50, 11),
            new ProgSeed(32, 0, "Closing Ceremony & Awards",
                    "Panel feedback from industry judges, cohort awards, and closing remarks.",
                    "Egbo Precious", "CTO, Semicolon Africa.",
                    490, 30, 12)
    );

    // ─── seeding ─────────────────────────────────────────────────────────────

    void seed(List<List<Events>> eventsByUser) {
        for (ProgSeed ps : PROGRAMME_SEEDS) {
            if (ps.organiserIndex() >= eventsByUser.size()) continue;
            List<Events> userEvents = eventsByUser.get(ps.organiserIndex());
            if (ps.eventIndex() >= userEvents.size()) continue;
            Events event = userEvents.get(ps.eventIndex());
            saveProgSeed(ps, event);
        }
        log.info("Seeded {} programme items", PROGRAMME_SEEDS.size());
    }

    void seedDreamDevProgramme(Events dreamDevEvent) {
        for (ProgSeed ps : PROGRAMME_SEEDS) {
            if (ps.organiserIndex() != 32) continue;
            saveProgSeed(ps, dreamDevEvent);
        }
        log.info("Seeded DreamDev Test Demo programme items");
    }

    private void saveProgSeed(ProgSeed ps, Events event) {
        LocalDateTime start = event.getStartTime().plusMinutes(ps.offsetMinutes());
        LocalDateTime end   = start.plusMinutes(ps.durationMinutes());
        programmeItemRepository.save(ProgrammeItem.builder()
                .event(event)
                .title(ps.title())
                .description(ps.description())
                .speakerName(ps.speakerName())
                .speakerBio(ps.speakerBio())
                .startTime(start)
                .endTime(end)
                .displayOrder(ps.displayOrder())
                .build());
        log.debug("Seeded programme item: [{}] {}", event.getTitle(), ps.title());
    }
}
